save change log state for v0.12.0 release announcement, update pre-commit hook (dont forget to update your local copy)

diff --git a/utils/pre-commit b/utils/pre-commit
--- a/utils/pre-commit
+++ b/utils/pre-commit
@@ -14,39 +14,39 @@
 # number) and create a GIT tag.
 
 if [ -f src/info.py ]; then
-
 	INFO_PY="src/info.py"
 elif [ -f cnchi/info.py ]; then
-    INFO_PY="cnchi/info.py"
+	INFO_PY="cnchi/info.py"
 else
-    INFO_PY="False"
+	INFO_PY="False"
 fi
 
 
 if [[ ${INFO_PY} != "False" ]]; then
-    BASE_STRING=$(python ${INFO_PY})
-    BASE_LIST= ($(echo $BASE_STRING | tr '.' ' ' ))
-    V_MAJOR=${BASE_LIST[0]}
-    V_MINOR=${BASE_LIST[1]}
-    V_PATCH=${BASE_LIST[2]}
-    echo "Current version : $BASE_STRING"
-    if [[ $V_PATCH = '' ]]; then
-        V_PATCH=0
-    else
-        V_PATCH=$((V_PATCH + 1))
-    fi
-    SUGGESTED_VERSION="$V_MAJOR.$V_MINOR.$V_PATCH"
+	BASE_STRING=$(python ${INFO_PY})
+	BASE_LIST=($(echo $BASE_STRING | tr '.' ' ' ))
+	V_MAJOR=${BASE_LIST[0]}
+	V_MINOR=${BASE_LIST[1]}
+	V_PATCH=${BASE_LIST[2]}
+	echo "Current version : $BASE_STRING"
+	if [[ $V_PATCH = '' ]]; then
+		V_PATCH=0
+	else
+		V_PATCH=$((V_PATCH + 1))
+	fi
+	SUGGESTED_VERSION="$V_MAJOR.$V_MINOR.$V_PATCH"
 
-    echo "Will set new version to be $SUGGESTED_VERSION"
-    sed -i "s|$BASE_STRING|$SUGGESTED_VERSION|g" ${INFO_PY}
-    git log --pretty=format:"[%ai] %<(69,trunc) %s %><(15) %aN {%h}" --cherry-pick "v0.10.0"...HEAD > CHANGES
-    git add CHANGES ${INFO_PY}
-    #git commit -m "Version bump to $INPUT_STRING"
-    #git tag -a -m "Tagging version $INPUT_STRING" "v$INPUT_STRING"
-    #git push origin
-    exit 0;
+	echo "Will set new version to be $SUGGESTED_VERSION"
+	sed -i "s|$BASE_STRING|$SUGGESTED_VERSION|g" ${INFO_PY}
+	git log --pretty=format:"[%ai] %<(69,trunc) %s %><(15) %aN {%h}" --cherry-pick "v0.10.0"...HEAD > CHANGES
+	git add CHANGES ${INFO_PY}
+	#git commit -m "Version bump to $INPUT_STRING"
+	#git tag -a -m "Tagging version $INPUT_STRING" "v$INPUT_STRING"
+	#git push origin
+	exit 0;
 else
-    echo "Could not find a VERSION file"
-    exit 1;
+	echo "Could not find a VERSION file"
 
 fi
+
+exit 1;
